### ISSUE TITLE
Can you update README

### ISSUE THREAD

**Issue by swiezaczek** [truongvinht/tgtg-checker#1]
1.How to add ENV's? - is it just file ".env" with content formatted like this:
TGTG_ACCESS_TOKEN=value
TGTG_REFRESH_TOKEN=value2
etc.. ?

2.What is REQ_TIMER and whats difference betwen this and DELAY?

3.How do I know script is working? I started it with by running node app.js, but literally nothing is happening - just "_" blinking and I dont get any notifications despite item is available and on my list in .env file formatted like:
ITEMS=["00000","11111"]
Thank you

**Comment by truongvinht** [comment]
In order to access the non-public API you need both tokens. But be aware they expire after a certain time.

Hint: try to look for tgtg python version on github to figure out how to get these tokens

**Comment by truongvinht** [comment]
read me updated
